application: website-template-1384
version: 1
runtime: go
api_version: go1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?.*\.map
- ^(.*/)?.*\.sh
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^\.git/.*
- \.editorconfig
- \.gitignore
- ^gulpfile\.js
- ^htmlhintrc\.json
- ^karma\.conf\.json
- ^package\.json
- ^README\..*
- ^tsconfig\.json
- ^typings\.json
- ^webpack\.config\.json
- ^dev/(.*/)?
- ^typings/(.*/)?
- ^node_modules/(.*/)?

handlers:
- url: /(.*\.html)
  mime_type: text/html
  static_files: public/\1
  upload: public/(.*\.html)

- url: /(.*\.css)
  mime_type: text/css
  static_files: public/\1
  upload: public/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: public/\1
  upload: public/(.*\.js)

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: public/\1
  upload: public/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: public/\1
  upload: public/(.*\.ico)

- url: /(.*\.ttf)
  mime_type: font/truetype
  static_files: public/\1
  upload: public/(.*\.ttf)

- url: /(.*\.woff)
  mime_type: application/x-font-woff
  static_files: public/\1
  upload: public/(.*\.woff)

- url: /lib
  static_dir: public/lib

- url: /.*
  script: _go_app
